#!/bin/sh
i3-msg -t subscribe -m '{"type":"workspace"}' |
while read -r _; do
    workspaces_info=$(i3-msg -t get_workspaces)
    focused_workspaces=$(echo "$workspaces_info" | jq --unbuffered -r '.[] | select(.focused == true).name')
    echo "$focused_workspaces"
done